language: c
dist: xenial
addons:
  # We run our builds sequentially in one VM rather than try and use the
  # matrix feature. This is because Travis is unreasonably inefficient
  # doing this APT setup pass.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - debhelper
      - dh-systemd
      - fakeroot
      - gcc-8
      - git-core
      - libnl-3-dev
      - libnl-route-3-dev
      - libudev-dev
      - make
      - ninja-build
      - pandoc
      - python-docutils
      - pkg-config
      - python
      - valgrind
      - sparse
      - wget
      - abi-compliance-checker
      - abi-dumper

      # 32 bit support packages
      - gcc-multilib
      # xenial craziness, need to give specific version of multilib,
      # in addition to general multilib
      - gcc-8-multilib
      - lib32gcc-8-dev

      # pyverbs
      - python3-dev
      - python3-pip

before_script:
  - http_proxy= pip3 install cython
script:
  - buildlib/travis-build
