language: c
dist: xenial
addons:
  # We run our builds sequentially in one VM rather than try and use the
  # matrix feature. This is because Travis is unreasonably inefficient
  # doing this APT setup pass.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - debhelper
      - dh-systemd
      - fakeroot
      - gcc-8
      - git-core
      - libnl-3-dev
      - libnl-route-3-dev
      - libudev-dev
      - make
      - ninja-build
      - pandoc
      - python-docutils
      - pkg-config
      - python
      - valgrind
      - sparse
      - wget
      - abi-compliance-checker
      - abi-dumper

      # 32 bit support packages
      - gcc-multilib
      # xenial craziness, need to give specific version of multilib,
      # in addition to general multilib
      - gcc-8-multilib
      - lib32gcc-8-dev

      # pyverbs
      - python3-dev
      - python3-pip

service:
    - docker

before_script:
  - export LATEST_GCC_LINARO_URL=`wget -qO - https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/ | grep -o '<a href=['"'"'"].*gcc-linaro-.*x86_64_aarch64-linux-gnu.tar.xz['"'"'"]'  |  sed -e 's/^<a href=["'"'"']//' -e 's/["'"'"']$//' | sort -n | tail -n 1`
  - export LATEST_GCC_LINARO_TAR=`basename $LATEST_GCC_LINARO_URL`
  - wget -q http://releases.linaro.org/$LATEST_GCC_LINARO_URL
  - mkdir $HOME/aarch64 && tar xf $LATEST_GCC_LINARO_TAR -C $HOME/aarch64 --strip 1
  - rm $LATEST_GCC_LINARO_TAR
  - http_proxy= pip3 install cython
script:
  - buildlib/travis-build
  - buildlib/travis-checkpatch
  - buildlib/package-build-test
